version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: devhelper
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: devhelper_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devhelper -d devhelper_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - ENV=testing
      - DATABASE_URL=postgresql+asyncpg://devhelper:secretpassword@postgres:5432/devhelper_test
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    command: >
      sh -c "python -m scripts.create_db &&
            pytest tests/ -n 1 &&
            uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
  redis_data: